### PR TITLE
RFC: Datepicker

### PR DESCRIPTION
**Pull request by pearofducks**
Rendered: https://github.com/fabric-ds/issues/blob/datepicker/rfcs/0002-datepicker.md

### CODE REVIEW

**Comment by digitalsadhu** [comment]
Fabric is about building blocks and not high level components so I believe this sort of approach the way to go. 

I don't have much experience implementing date pickers but architecturally speaking, it feels to me like providing a set of building blocks (be they components and/or builder functions) with a basic reference implementation or 2 is key because:
* teams with more advanced use cases
  * can get a consistent look/feel and not need to reinvent the wheel from scratch. 
  * have a good example to work from in the reference implementations
* teams with simple use cases can get something other of the box

Side note, we could consider building a more advanced implementation for (or work with) other teams with high level needs in order to design and refine our lower level building blocks underway. ie. To make sure we are building the right thing that can support such needs.

**Comment by digitalsadhu** [comment]
With regards to the existing Troika date picker. Discussion this morning seemed to be leaning toward porting the existing date picker to Fabric as is but to keep it external to Fabric itself. ie. maintain it as a separate project for now but update it to use Fabric. 

We would then continue to work on a set of Fabric date picker building blocks and reference/simple implementation separately.

Do we all agree on this approach?
@pearofducks @Skadefryd @benja @martin-storsletten @adidick ?

**Comment by adidick** [comment]
Sounds like a good plan to me

**Comment by benja** [comment]
Yeah, this seems like a good plan to me. :)

**Comment by digitalsadhu** [comment]
We seem to have general agreement on the proposal. Think I'll merge and we can make further adjustments if needed.

**Pull request merged**
